# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-24 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='my_games',
            field=models.ManyToManyField(to='store.Game'),
        ),
    ]
