# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-24 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_my_games'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='my_games',
            field=models.ManyToManyField(blank=True, to='store.Game'),
        ),
    ]
